services:
    application:
        build:
            context: .
            dockerfile: dockerfiles/php/Dockerfile
        image: application
        container_name: application
        tty: true
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www
        depends_on:
            - mysql
        command: >
            bash -c "
            composer install &&
            php artisan key:generate &&
            php artisan migrate &&
            php-fpm"
        networks:
            - laravel_app
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "${APP_PORT}:80"
        volumes:
            - .:/var/www
            - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel_app
    mysql:
        image: mysql:5.7
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        networks:
            - laravel_app
networks:
    laravel_app:
        driver: bridge
